spring:
  profiles:
    active: git, vault
  rabbitmq:
    host: ${vault.rabbitmq_host}
    port: ${vault.rabbitmq_port}
    username: ${vault.rabbitmq_username}
    password: ${vault.rabbitmq_password}
  cloud:
    config:
      server:
        vault:
          order: 1
          host: localhost
          port: 8200
          token: ${VAULT_TOKEN}
          authentication: token
          kv-version: 2
          backend: config-service-secret
          profile-separator: '/'
          scheme: http
        native:
          search-locations: ${vault.native_location}
        git:
          uri: https://github.com/Kyumin-Chang/zipbob-config-repo
          search-paths:
            - '{application}'
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true

management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh
